import Head from "next/head";
import Hero from "../components/hero";

export default function Home() {
   return (
      <div className="fullpage">
         <header className="header">
            <Head>
               <title>Mami Nishiwaki, Developer</title>
               <meta
                  name="description"
                  content="Generated by create next app"
               />
               <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
         </header>
      </div>
   );
}
